@api = http://localhost:3000/v1-api/users
//@api = https://app-pizzeria-mysql.herokuapp.com/v1-api/users
@token = 


### todos los usuarios
GET  {{api}}/
x-access-token : {{token}}

### crear usuario
POST  {{api}}/
x-access-token : {{token}}

{
    "name":"",
    "email":"",
    "password":""
}

### login de un usuario
POST  {{api}}/login
x-access-token : {{token}}
content-type: application/json

{
    "email":"",
    "password":""
}